spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://192.168.65.128:3306/user_center?useSSL=false'
    username: root
    password: root
  session:
    timeout: 86400